fixed change-enc on unifi ac lite ap

diff --git a/aps/configs/openwrt/unifi-ac-lite/usr/bin/change-enc b/aps/configs/openwrt/unifi-ac-lite/usr/bin/change-enc
--- a/aps/configs/openwrt/unifi-ac-lite/usr/bin/change-enc
+++ b/aps/configs/openwrt/unifi-ac-lite/usr/bin/change-enc
@@ -9,6 +9,12 @@ then
 	exit 1
 fi
 
+if [ "$1" != "open" ] && [ "$1" != "wpa2" ]
+then
+	echo "error : unrecognized wpa-encryption : $1"
+	exit 1
+fi
+
 freq=1
 if [ "$2" = "2.4" ]
 then
@@ -17,7 +23,7 @@ elif [ "$2" = "5" ]
 then  
 	freq=40
 else
-	echo "error : unrecognized freq-band :  $freq"
+	echo "error : unrecognized freq-band : $2"
 	exit 1
 fi
 
